spring:
  application:
    name: ms-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG

