server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gigi-U/config-server-keycloak-springboot3-application-part1
          force-pull: true
          search-paths: configData
